//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityCoches
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraVenta
    {
        public int ID_CompraVenta { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal Precio { get; set; }
        public string tipo { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public Nullable<int> ID_VEHICULO { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
